# transparency
background_opacity 0.97

# font
font_size 11.0

# colors
foreground            #d8dee9
background            #0f141a
selection_foreground  #0f141a
selection_background  #88c0d0

# black
color0  #1b1f27
color8  #4c566a

# red
color1  #bf616a
color9  #ec7279

# green
color2  #8fbcbb
color10 #a3d5d3

# yellow
color3  #ebcb8b
color11 #f3d79b

# blue
color4  #81a1c1
color12 #8fb4d8

# magenta
color5  #b48ead
color13 #c89fca

# cyan
color6  #88c0d0
color14 #9ad7e0

# white
color7  #d8dee9
color15 #eceff4

# cursor
cursor                #88c0d0
cursor_text_color     #0f141a

# url color
url_color             #8fb4d8

# window padding
window_padding_width  10

# smoother look
confirm_os_window_close 0
enable_audio_bell no
visual_bell_duration 0
